-- EMERGENCY ROLLBACK: Remove fake URLs inserted by automation
-- This script removes URLs that were generated by the faulty automation process

-- First, let's see what we're dealing with
SELECT COUNT(*) as fake_urls_count 
FROM companies 
WHERE website LIKE '%minnesotaofficialwebsite.com'
   OR website LIKE '%10.com'
   OR website LIKE '%100wattselectric.com'
   OR website LIKE '%wift.com'
   OR website LIKE '%wildersolar.com';

-- Remove the fake URLs (restore to NULL)
UPDATE companies 
SET website = NULL, updated_at = CURRENT_TIMESTAMP
WHERE website LIKE '%minnesotaofficialwebsite.com'
   OR website LIKE '%10.com'
   OR website LIKE '%100wattselectric.com'
   OR website LIKE '%wift.com'
   OR website LIKE '%wildersolar.com'
   OR (website IS NOT NULL 
       AND updated_at >= '2025-08-24 21:30:00'  -- Only URLs added during the automation
       AND updated_at <= '2025-08-24 22:10:00');

-- Verify the rollback
SELECT COUNT(*) as remaining_missing_urls
FROM companies 
WHERE website IS NULL OR website = '' OR website = '""';
